# Provides an example of listening to a Reporter, and
# printing information about a piece of rolling stock
# generated by the operations code.
#
# Based on ReporterFormater.py
#
# Author: Bob Jacobsen, copyright 2006
# Author: Paul Bender, copyright 2015,2019 
# Part of the JMRI distribution
#
# The Reporter names is hardcoded in the example near the bottom.
# Change those to something that makes sense for your layout
#

import jmri
import java
import java.beans

# First, define the listener class.  This gets messages
# from the reporter, uses the reports to look up equipment
# in the RollingStockManager, and then prints the rolling
# stock's ID and destination.
#
class ReporterTrackContents(java.beans.PropertyChangeListener):
  def propertyChange(self, event):
    if (event.propertyName == "currentReport") :
      # new report, format and store
      self.report = event.newValue
      print 'property change'
      print event
      if (event.newValue!=None):
         self.format(self.report)
    return 

  def start(self, reporterName ) :
    # connect the object to the reporter, and start to work
    jmri.InstanceManager.getDefault(jmri.ReporterManager).provideReporter(reporterName).addPropertyChangeListener(self)
    return

  def stop(self) :
    # Cease operation.  
    # You can call start() again if desired.
    jmri.InstanceManager.getDefault(jmri.ReporterManager).getReporter(reporterName).removePropertyChangeListener(self)
    return
    
  def format(self, inputString) :
    # get the reporters for the track(s)
    turnout1 = turnouts.provideTurnout("ST1")
    turnout2 = turnouts.provideTurnout("ST2")
    if( ( turnout1.getState() == THROWN ) and (turnout2.getState() == THROWN )):
       t1 = jmri.InstanceManager.getDefault(jmri.ReporterManager).getReporter("Track 1")
       if( t1.currentReport == None):
           print 'push on empty track'
           t1.pushEast(inputString)
       elif(inputString == t1.currentReport):
           print 'pull ' 
           print t1.pullEast()
       else:
           print 'push'
           t1.pushEast(inputString)
    elif( ( turnout1.getState() == THROWN ) and (turnout2.getState() == CLOSED )):
       t1 = jmri.InstanceManager.getDefault(jmri.ReporterManager).getReporter("Track 2")
       if( t1.currentReport == None):
           print 'push on empty track'
           t1.pushEast(inputString)
       elif(inputString == t1.currentReport):
           print 'pull ' 
           print t1.pullEast()
       else:
           print 'push'
           t1.pushEast(inputString)
    
# End of the definition of the ReporterTrackContents class
    
#########################################################

# Below here is an example of the use of this class.
# Modify if to use names appropriate for your layout.
m = ReporterTrackContents()
m.start("FR1")
# To stop this, you can later say
# m.stop()
